Update up

diff --git a/up b/up
--- a/up
+++ b/up
@@ -3,4 +3,7 @@
 set -e
 
 echo -e "\nStarting update\n"
-sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y && echo -e "\nUpdate done\n" || echo -e "\nUpdate Failed\n"
+        sudo apt update && \
+        sudo apt upgrade -y && \
+        sudo apt autoremove -y && \
+        echo -e "\nUpdate done\n" || echo -e "\nUpdate Failed\n"
